genernal: 
  query_limit:
    maxium: 200
    minimal: 10

databases: 
  ip: '127.0.0.1'
  port: 27017
  db_name: expo_shop

all_salt:
  jwt_salt: "Sample!Salt#Do*Not*Use*This*Salt"
  local_password_salt: "Sample!passwd_salt!DoNot?Use?This*Salt"
  hmac_salt: "Sample!hmac_salt!DoNot~Use#This&Salt"